version: '3.1'
services:
    elk:
      image: sebp/elk
      ports:
        - "5601:5601"
        - "9200:9200"
        - "9600:9600"
        - "5044:5044"
    jupyter-pyspark:
      image: jupyter/pyspark-notebook
      ports:
        - "8888:8888"
        - "9999:9999"
        - "4040:4040"
        - "4141:4141"
      volumes:
        - /work:/home/jovyan/work
# sudo sysctl -w vm.max_map_count=262144